# syntax=docker/dockerfile:1

FROM ubuntu

RUN apt update && \
    apt -y install sudo

RUN useradd -m vscode && echo "vscode:vscode" | chpasswd \
	&& adduser vscode sudo \
	&& groupadd docker \
	&& usermod -aG docker vscode

RUN echo "vscode ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

CMD['bash']

USER vscode
